### ISSUE TITLE
testpypi deployment fails (deprecated API)

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#197]
Travis CI is configured to deploy the state of the master branch to testpypi. This is valuable to test the release process before doing an actual release. Unfortunately, this [doesn't work][travis-error]:

> Uploading distributions to https://testpypi.python.org/pypi
> Uploading gcovr-3.3-py2-none-any.whl
> HTTPError: 410 Client Error: Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html) for url: https://testpypi.python.org/pypi

  [travis-error]: https://travis-ci.org/gcovr/gcovr/jobs/330012531#L1239

The currently used .travis.yml states:

``` yml
deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: whart111
    password:
      secure: ...
    distributions: sdist --format=gztar bdist_wheel
    on:
      tags: false
      branch: master
      python: '2.7'
```

PyPI deployment from Travis CI is documented here: https://docs.travis-ci.com/user/deployment/pypi/
… but that doesn't shed any light on this problem :(

Would someone like to try fixing this? Because a pull request addressing this problem can't be tested before merging, please:

 - explain why the problem occurred,
 - explain why the pull request will fix this,
 - point to the relevant Travis and PyPI documentation, and
 - if possible, point to another project using the proposed solution, where upload demonstrably works.

I will then be happy to assist by reviewing, merging, and iterating proposed changes until this works.
